# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwidtUI_Dise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwidtUI_Dise

  target 'SwidtUI_DiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwidtUI_DiseUITests' do
    # Pods for testing
  end

pod 'Contentful', '~> 5.0.0'
pod 'SDWebImageSwiftUI'
pod  'lottie-ios'


end
